<?php
// src/OC/PlatformBundle/Repository/ApplicationRepository.php

namespace OC\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getApplicationsWithAdvert($limit)
    {
      $qb = $this
        ->createQueryBuilder('a')
        ->leftJoin('a.advert', 'adv')
        ->addSelect('adv')
        ->orderBy('a.date', 'DESC')
        ->setMaxResults( $limit )
      ;

      return $qb
              ->getQuery()
              ->getResult()
          ;
    }
        
}